# Site
repository: mantasalonderis/mycv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mantas Alonderis
title: Observability Engineer
email: mantas.alonderis@gmail.com
phone: (267) 777-7150
website: https://malond11.github.io/resume/
location: Philadelphia, PA

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username: Malond11
# stackoverflow_username: 
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# instagram_username: 
linkedin_username: mantas-alonderis
# xing_username: 
# pinterest_username: 
# youtube_username: 
# googleplus_username: 
# orcid_username: 

# Additional icon links
additional_links:
- title: Download PDF Resume
  icon: fas fa-file-pdf
  url: /assets/Mantas_Alonderis_Resume.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Versatile Software Development engineer adept at building and maintaining robust, scalable infrastructure and data solutions. Proficient in AWS, Terraform, and observability tools (DataDog, Elasticsearch). Experienced in implementing CI/CD pipelines, optimizing system reliability, and architecting data workflows. Excels in process automation and resolving complex operational issues. Leverages unique background in embedded systems to enhance performance and reliability across infrastructure and data ecosystems.

  I am most skilled in: <mark>AWS</mark>, <mark>Terraform</mark>, <mark>Python</mark>, <mark>Data Observability</mark>, and <mark>CI/CD Pipelines</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: API Framework for Telemetry Analytics
        # link: comcast.com
        # link_text: Project Website
        # additional_links:
        #   - title:  
        #     icon: 
        #     url: 
        quote: >
          A high-performance RESTful API framework processing telemetry data from millions of RDK devices for in-house AI tools.
        description: | # this will include new lines to allow paragraphs
          Architected and implemented a high-performance RESTful API framework that processes telemetry data from millions of RDK devices and was used in in-house AI tools. This Flask-based service provided critical analytics capabilities through AWS-hosted microservices, enabling real-time monitoring and anomaly detection for large-scale device deployments.

          **Key Contributions:**
          
          - Developed critical API endpoints that powered internal company AI chatbots and analytics applications, enabling efficient analysis of device telemetry and feature flag performance across **millions of devices**
          - Implemented comprehensive AWS infrastructure leveraging S3, Athena, Glue Data Catalog, and Aurora databases to process and analyze **terabytes of device telemetry data**
          - Containerized the application using Docker and orchestrated automated deployments via AWS Elastic Beanstalk and Concourse CI/CD pipelines
          - Developed a modular, extensible framework using Flask-RESTX that enabled rapid integration of new analytics endpoints while maintaining clear separation of concerns
          - Enhanced system observability by implementing query execution metrics, custom response headers, and detailed logging for performance monitoring
          - Optimized database query patterns for AWS Athena, resulting in **significant cost reduction** and improved query efficiency for large datasets
          
          **Technologies:** <mark>Python</mark>, <mark>Flask</mark>, <mark>AWS</mark> (S3, Athena, Glue, Aurora, Elastic Beanstalk), <mark>Docker</mark>, <mark>Concourse CI/CD</mark>, <mark>SQL</mark>, <mark>RESTful API</mark>, <mark>Pandas</mark>, <mark>Data Analytics</mark>, <mark>Telemetry Processing</mark>

      - layout: top-middle
        title: Comprehensive Data Observability and Anomaly Detection System
        # link: comcast.com
        # link_text: Project Website
        # additional_links:
        #   - title:  
        #     icon: 
        #     url: 
        quote: >
          A robust system that slashed anomaly detection time by 60% and issue resolution time by 40%.
        description: | # this will include new lines to allow paragraphs
          Architected monitoring infrastructure using Terraform, AWS services (CloudWatch, Lambda, SNS, SQS, S3), and Datadog. Implemented CI/CD pipelines with GitHub Actions, automating infrastructure and configuration updates. Optimized data pipelines using Apache Spark, enhancing large-scale data processing and analysis efficiency. 
          
          **Key Achievements:**
          
          - Developed machine learning models for predictive analytics, improving trend forecasting accuracy
          - Integrated custom alerting mechanisms with messaging services via webhooks and APIs, enhancing incident response
          - Implemented Elasticsearch and Kibana for application-level logging and performance visualization
          - Slashed anomaly detection time by **60%** and issue resolution time by **40%** through advanced algorithms
          - Boosted system reliability by **25%** with automated issue resolution and continuous monitoring
          - Achieved **99.99% uptime** for critical data pipelines through robust infrastructure and efficient alerting mechanisms
          
          **Technologies:** <mark>Terraform</mark>, <mark>AWS</mark> (CloudWatch, Lambda, SNS, SQS, S3), <mark>Datadog</mark>, <mark>GitHub Actions</mark>, <mark>Apache Spark</mark>, <mark>Machine Learning</mark>, <mark>Elasticsearch</mark>, <mark>Kibana</mark>

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Comcast
        link: comcast.com
        # link_text: comcast.com
        sub_title: Data Observability Engineer
        caption: August 2023 - Present
        quote: >
          Spearheaded transition from embedded systems to data observability, applying expertise in data analysis and system optimization.
        description: | # this will include new lines to allow paragraphs
          **Key Responsibilities:**
          - Established Git and GitHub workflows for source code management, enhancing code quality and team collaboration
          - Optimized CI/CD pipelines using Github Actions or AWS CodePipeline, reducing deployment times by **40%** and increasing release frequency
          - Designed and implemented comprehensive data observability solutions
          - Built AWS, Terraform, and DataDog monitoring systems
          - Developed real-time data health dashboards and KPI tracking systems
          - Implemented end-to-end data lineage tracking
          - Led mentorship programs on data observability best practices
          
          **Key Achievements:**
          - Engineered data collection and analysis processes for edge devices, elevating data quality by **40%**
          - Architected advanced anomaly detection algorithms, cutting false positive alerts by **60%**
          - Led collaboration between hardware and data science teams, boosting system performance by **25%**
          - Pioneered application of machine learning techniques from signal processing, accelerating system failure detection by **30%**
          - Decreased data-related incidents by **35%**
          - Achieved **99.9% visibility** into critical data pipelines
          - Slashed issue detection time by **50%**

      - layout: left
        title: Comcast
        link: comcast.com
        # link_text: comcast.com
        sub_title: Broadband Embedded System Analysis and Triage Squad Lead
        caption: January 2022 - July 2023
        quote: >
          Led WiFi service optimization team, automating triage processes to boost productivity by 15%.
        description: | # this will include new lines to allow paragraphs
          **Key Responsibilities:**
          - Implemented QA processes for firmware stability, specializing in WiFi anomaly detection and resolution
          - Automated device performance data analysis workflows with SQL and Python scripts
          - Developed Python scripts to automate WiFi anomaly triage
          
          **Key Achievements:**
          - Boosted productivity by **15%**
          - Reduced triage times by **10%**
          - Significantly enhanced squad efficiency

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Vilnius Gediminas Technical University
        location: Vilnius, Lithuania
        caption: 2021
        sub_title: Bachelor's in Telecommunications Engineering, Minor in Electronics Engineering
        quote: >
          GPA: 3.7
        description: | # this will include new lines to allow paragraphs
          Studied telecommunications and electronics engineering, developing skills in embedded systems, signal processing, and networking that I've leveraged throughout my career.

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Technical Skills**: <mark>Embedded Systems</mark>, <mark>Signal Processing</mark>, <mark>AWS</mark> (Lambda, DynamoDB, S3, SNS, CloudWatch, Cloudformation), <mark>Terraform</mark>, <mark>Apache Spark</mark>, <mark>Python</mark>, <mark>SQL</mark>, <mark>Elasticsearch</mark>, <mark>ELK Stack</mark>, <mark>Splunk</mark>, <mark>Kibana</mark>, <mark>DataDog</mark>, <mark>Grafana</mark>, <mark>Promethius</mark>, <mark>GitHub Actions</mark>, <mark>Docker</mark>, <mark>Kubernetes</mark>, <mark>OpenAPI</mark>
      
      **Data Management**: <mark>Data Quality Monitoring</mark>, <mark>Anomaly Detection</mark>, <mark>Log Analysis</mark>, <mark>Data Lineage Tracking</mark>, <mark>SLA Management</mark>
      
      **Data Engineering**: <mark>ETL Pipelines</mark>, <mark>Data Warehousing</mark>, <mark>Real-time Data Processing</mark>
      
      **Domain Expertise**: <mark>Broadband Systems</mark>, <mark>Network Protocols</mark>, <mark>IoT Data Analytics</mark>
      
      **Soft Skills**: <mark>Leadership</mark>, <mark>Communication</mark>, <mark>Problem-solving</mark>, <mark>Decision-making</mark>, <mark>Cross-functional Collaboration</mark>
      
      **Languages**: <mark>English</mark>, <mark>Russian</mark>, <mark>Lithuanian</mark>

  - title: Interests
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Sports**: <mark>BJJ</mark>, <mark>Soccer</mark>, <mark>Basketball</mark>
      
      **Building**: <mark>Woodworking</mark>, <mark>Building Science</mark>
      
      **Open Source**: <mark>All of it</mark>

  - title: Contact Information
    layout: text
    content: | # this will include new lines to allow paragraphs
      Email: mantas.alonderis@gmail.com
      
      Phone: (267) 777-7150
      
      Web: https://malond11.github.io/mycv/
      
      Location: Philadelphia, PA

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag