# Site
repository: mantasalonderis/mycv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mantas Alonderis
title: Data Observability Engineer
email: mantas.alonderis@gmail.com
website: www.github.com/mantasalonderis

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username: mantasalonderis
# stackoverflow_username: 
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# instagram_username: 
linkedin_username: mantas-alonderis
# xing_username: 
# pinterest_username: 
# youtube_username: 
# googleplus_username: 
# orcid_username: 

# Additional icon links
# additional_links:
# - title: 
#   icon: 
#   url: 
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Mantas and I'm a Data Observability Engineer at Comcast. I specialize in building and maintaining robust, scalable infrastructure and data solutions. I have experience in implementing CI/CD pipelines, optimizing system reliability, and architecting data workflows.

  I am most skilled in: <mark>AWS</mark>, <mark>Terraform</mark>, and <mark>Data Observability</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Comprehensive Data Observability and Anomaly Detection System
        link: comcast.com
        # link_text: Project Website
        # additional_links:
        #   - title:  
        #     icon: 
        #     url: 
        quote: >
          A robust system that slashed anomaly detection time by 60% and issue resolution time by 40%.
        description: | # this will include new lines to allow paragraphs
          I architected monitoring infrastructure using Terraform, AWS services (CloudWatch, Lambda, SNS, SQS, S3), and Datadog. Implemented CI/CD pipelines with GitHub Actions, optimized data pipelines using Apache Spark, and developed machine learning models for predictive analytics. The system achieved 99.99% uptime for critical data pipelines through robust infrastructure and efficient alerting mechanisms.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Comcast
        link: comcast.com
        # link_text: comcast.com
        sub_title: Data Observability Engineer
        caption: August 2023 - Present
        quote: >
          Spearheaded transition from embedded systems to data observability, applying expertise in data analysis and system optimization.
        description: | # this will include new lines to allow paragraphs
          Engineered data collection and analysis processes for edge devices, elevating data quality by 40%. Architected advanced anomaly detection algorithms, cutting false positive alerts by 60%. Led collaboration between hardware and data science teams, boosting system performance by 25%. Established Git and GitHub workflows for source code management, enhancing code quality and team collaboration. Designed and implemented comprehensive data observability solutions, decreasing data-related incidents by 35%.

      - layout: left
        title: Comcast
        link: comcast.com
        # link_text: comcast.com
        sub_title: Broadband Embedded System Analysis and Triage Squad Lead
        caption: January 2022 - July 2023
        quote: >
          Led WiFi service optimization team, automating triage processes to boost productivity by 15%.
        description: | # this will include new lines to allow paragraphs
          Implemented QA processes for firmware stability, specializing in WiFi anomaly detection and resolution. Automated device performance data analysis workflows with SQL and Python scripts, reducing triage times by 10%. Developed Python scripts to automate WiFi anomaly triage, significantly enhancing squad efficiency.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Vilnius Gediminas Technical University
        caption: 2021
        sub_title: Bachelor's in Telecommunications Engineering, Minor in Electronics Engineering
        quote: >
          GPA: 3.7
        description: | # this will include new lines to allow paragraphs
          Studied telecommunications and electronics engineering, developing skills in embedded systems, signal processing, and networking that I've leveraged throughout my career.

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Technical Skills**: <mark>Embedded Systems</mark>, <mark>Signal Processing</mark>, <mark>AWS</mark>, <mark>Terraform</mark>, <mark>Apache Spark</mark>, <mark>Python</mark>, <mark>SQL</mark>, <mark>Elasticsearch</mark>, <mark>Kibana</mark>, <mark>DataDog</mark>, <mark>Grafana</mark>, <mark>GitHub Actions</mark>, <mark>Docker</mark>, <mark>Kubernetes</mark>
      
      **Data Management**: <mark>Data Quality Monitoring</mark>, <mark>Anomaly Detection</mark>, <mark>Log Analysis</mark>, <mark>Data Lineage Tracking</mark>, <mark>SLA Management</mark>
      
      **Data Engineering**: <mark>ETL Pipelines</mark>, <mark>Data Warehousing</mark>, <mark>Real-time Data Processing</mark>
      
      **Domain Expertise**: <mark>Broadband Systems</mark>, <mark>Network Protocols</mark>, <mark>IoT Data Analytics</mark>
      
      **Soft Skills**: <mark>Leadership</mark>, <mark>Communication</mark>, <mark>Problem-solving</mark>, <mark>Decision-making</mark>, <mark>Cross-functional Collaboration</mark>
      
      **Languages**: <mark>English</mark>, <mark>Russian</mark>, <mark>Lithuanian</mark>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag